import Head from "next/head";
import dynamic from "next/dynamic";

import { Container, Grid } from "semantic-ui-react";
import { SubstrateContextProvider } from "context/SubstrateContext";

const AccountSelector = dynamic(
  () => import("example-components/AccountSelector"),
  {
    ssr: false
  }
);
const NodeInfo = dynamic(() => import("example-components/NodeInfo"), {
  ssr: false
});
const Metadata = dynamic(() => import("example-components/Metadata"), {
  ssr: false
});
const BlockNumber = dynamic(() => import("example-components/BlockNumber"), {
  ssr: false
});
const Daos = dynamic(() => import("example-components/Daos"), {
  ssr: false
});
const Balances = dynamic(() => import("example-components/Balances"), {
  ssr: false
});
const Transfer = dynamic(() => import("example-components/Transfer"), {
  ssr: false
});
const Upgrade = dynamic(() => import("example-components/Upgrade"), {
  ssr: false
});
const Interactor = dynamic(() => import("example-components/Interactor"), {
  ssr: false
});
const Events = dynamic(() => import("example-components/Events"), {
  ssr: false
});
const TemplateModule = dynamic(
  () => import("example-components/TemplateModule"),
  {
    ssr: false
  }
);
import DeveloperConsole from "../example-components/DeveloperConsole";
import { Icon } from "../components/ui-kit/Icon";

export default function Home() {
  return (
    <SubstrateContextProvider>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Icon name={"add"} color={"green"} />
        {/*<div>*/}
        {/*  <AccountSelector />*/}
        {/*  <Container>*/}
        {/*    <Grid stackable columns="equal">*/}
        {/*      <Grid.Row stretched>*/}
        {/*        <NodeInfo />*/}
        {/*        <Metadata />*/}
        {/*        <BlockNumber />*/}
        {/*        <BlockNumber finalized />*/}
        {/*      </Grid.Row>*/}
        {/*      <Grid.Row stretched>*/}
        {/*        <Daos />*/}
        {/*      </Grid.Row>*/}
        {/*      <Grid.Row stretched>*/}
        {/*        <Balances />*/}
        {/*      </Grid.Row>*/}
        {/*      <Grid.Row>*/}
        {/*        <Transfer />*/}
        {/*        <Upgrade />*/}
        {/*      </Grid.Row>*/}
        {/*      <Grid.Row>*/}
        {/*        <Interactor />*/}
        {/*        <Events />*/}
        {/*      </Grid.Row>*/}
        {/*      <Grid.Row>*/}
        {/*        <TemplateModule />*/}
        {/*      </Grid.Row>*/}
        {/*    </Grid>*/}
        {/*  </Container>*/}
        {/*  <DeveloperConsole />*/}
        {/*</div>*/}
      </main>
    </SubstrateContextProvider>
  );
}
